# Generated by Django 3.1.2 on 2020-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lecturer', models.CharField(max_length=40)),
                ('sks', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('semester', models.CharField(max_length=9)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
    ]
